---
title: "WECC Joint Quarto File"
author: Hyrum Hendrickson, Jonathan Ascona, Alex Tovar, Kouadio Ange Konan
format: html
editor: visual
---

## Western Electricity Coordinating Council Prediction Project

**Project Introduction: Predictive Maintenance for Electric Grids in Rexburg, Idaho**

In this project, we aim to develop a predictive model utilizing 20 years of historical data from the Western Electricity Coordinating Council (WECC) to anticipate maintenance needs for the electric grid infrastructure in Rexburg, Idaho. The reliable functioning of electric grids is critical for ensuring uninterrupted power delivery, and timely maintenance plays a crucial role in preventing outages and service disruptions. By analyzing patterns and anomalies within the WECC dataset, which includes information on power usage, grid failures, and environmental conditions, we seek to identify key indicators that signal when intervention may be required.

Our predictive maintenance model will provide the city of Rexburg with actionable insights, allowing it to optimize resource allocation and reduce downtime. The model will consider historical grid performance, weather data, and potential failure events to forecast when and where maintenance crews should be deployed. Through this project, we aim to enhance grid reliability, minimize service interruptions, and support Rexburg's goal of achieving an efficient and sustainable energy system.

------------------------------------------------------
